version: '2'
services:
  eurekaserver:
    image: microservices/eurekaserver:latest
    ports:
      - "8761:8761"
  configurationserver:
    image: microservices/configurationserver:latest
    ports:
       - "8888:8888"
    environment:
       EUREKASERVER_URI: "http://eurekaserver:8761/eureka/"
       EUREKASERVER_PORT: "8761"
      ENCRYPT_KEY: ${ENCRYPT_KEY}
  database:
    image: postgres:9.5
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB:       "eagle_eye_local"
  service1:
    image: microservices/service1:latest
    ports:
      - "8080:8080"
    environment:
      PROFILE: "default"
      EUREKASERVER_URI: "http://eurekaserver:8761/eureka/"
      EUREKASERVER_PORT: "8761"
      CONFIGSERVER_URI: "http://configurationserver:8888"
      CONFIGSERVER_PORT:   "8888"
      DATABASESERVER_PORT: "5432"
      ENCRYPT_KEY: ${ENCRYPT_KEY}
